name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    test_build:
        name: Build HB-1000
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Download Pico SDK
              run: git clone https://github.com/raspberrypi/pico-sdk.git
            
            - name: Get Pico SDK submodules
              working-directory: pico-sdk
              run: git submodule update --init
            
            - name: Get SDK import file
              run: cp pico-sdk/external/pico_sdk_import.cmake .

            - name: Build
              id: build
              uses: samyarsadat/Pico-Build-Action@v1
              with:
                  source_dir: "."
                  cmake_args: "-DCMAKE_BUILD_TYPE=Debug -DPICO_SDK_PATH=/github/workspace/pico-sdk"
                  board_name: "pico"
                  output_dir: "build"
                  output_ext: "*.uf2 *.elf *.elf.map"

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: workspace_artifacts
                  path: ${{steps.build.outputs.output_dir}}
